name: test
on: push
jobs:
  code-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Linter
      run: python3 -m pip install pylint black .[webserver]
    - name: black
      run: black --check --line-length 99 --skip-string-normalization setup.py waterfall
    - name: pylint
      run: pylint --min-public-methods=1 --disable=C0114,C0115,C0116 --fail-under 10 --max-line-length 99 setup.py waterfall
  ubuntu18:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Test
      run: bash .github/workflows/test_code.sh
  ubuntu20:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Test
      run: bash .github/workflows/test_code.sh
  ubuntu22:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Test
      run: bash .github/workflows/test_code.sh
  windows2019:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Test
      shell: cmd
      run: .github\workflows\test_code.cmd
  windows2022:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v2
    - name: Test
      shell: cmd
      run: .github\workflows\test_code.cmd
  macos11:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: install timeout
      run: |
        brew install coreutils
        alias timeout=gtimeout
    - name: Test
      run: bash .github/workflows/test_code.sh
