name: test
on: push
jobs:
  code-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Linter
      run: python3 -m pip install pylint black .[webserver]
    - name: Check Code
      run: bash check_code.cmd
  ubuntu18:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - run: bash test_code.cmd
  ubuntu20:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - run: bash test_code.cmd
  ubuntu22:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.10
    - run: bash test_code.cmd
  windows2019:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - run: test_code.cmd
  windows2022:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - run: test_code.cmd
  macos:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - run: bash test_code.cmd
